# WorkBook 2 

# Task 1.3.1

In [2]:
import numpy as np
array = np.array([[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1]])
print(array)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Task 1.3.2 

In [9]:
import numpy as np
array = np.zeros((5,5))
array += np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# Task 1.3.3

In [15]:
import numpy as np
array = np.random.randint(1000000,size=(3,3,3))
print(array)


[[[733560 413664 367875]
  [582557 651984 371950]
  [329905 283022 152104]]

 [[ 75622 578628 899761]
  [   844  86566 484859]
  [313917  34122  86613]]

 [[654785 649811 879716]
  [976507 954166 605885]
  [870048 403236 944348]]]


# Task 1.3.4

In [16]:
import numpy as np
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Task 1.3.5

In [19]:
import numpy as np
 array = np.random.randint(100,size=(10))
print(np.sort(array))

[ 4  7  8 12 27 43 79 84 86 97]


# Task 1.3.6

In [23]:
import numpy as np
array = np.random.randint(100,size=(10,5))
print(np.shape(array))
print(len(array))


(10, 5)
10


# Task 2.3.1

In [2]:
import numpy as np
import pandas as pd
x = pd.Series([1, 4, 6])
y = pd.Series([1, 3, 5])
print(np.linalg.norm(x-y))

1.4142135623730951


# Task 2.3.2

In [14]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'
dataframe = pd.read_csv(url)
dataframe.head(100)

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0   0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1   0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2   0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3   0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4   0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   
..    ...    ...  ...  ...  .. ..  ..  ...  ..  ...  ..  ..  ..  ..  ..  ..   
95  0.263  0.373   57  127  17  2  16   70  84  108   0  11   0   0   1   0   
96  0.248  0.286   24   56   5  2   2   13  12   35   2  11   1   1   0   0   
97  0.229  0.303   54  105  24  1  16   70  49   72   1   3   1   0   0   0   
98  0.267  0.296   60  155  22  3  17   87  23  114   8  14   0   0   1   1   
99  0.281  0.351   78  159  24  6   1   50  59   40  25  18   0   0   0   0   

    salary  
0      109  
1      160  
2     2700  
3      550  
4      300  
..     ...  
95    1200  
96     350  
97    2850  
98    3300  
99     360  

[100 rows x 17 columns]

# Task 2.3.3

In [21]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['2'] == '2'].head(2)

Empty DataFrame
Columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, salary]
Index: []

# Task 3.3.2

In [23]:
import pandas as pd
from sklearn import preprocessing
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 